### ISSUE TITLE
Remote access to AU workstation computer - ingesting & deleting images, updating species-ocr and species-web code

### ISSUE THREAD

**Issue by beckerah** [NHMDenmark/Mass-Digitizer#542]
Since we are taking over maintenance of Aksel's code, it would be useful if we could get remote access to the workstation computer at AU. We know this is how Aksel was working on it before he left, so it's definitely possible. @PipBrewer - We will need to get a login from AU IT as a first step. Is this something that we can facilitate through Birgitte? 

Having access to the computer will also help us work with the ingestion client, (installing updates, checking error logs, etc.) And it will give us direct access to the image files, which could be useful for dealing with future issues.

**Comment by beckerah** [comment]
Bhupjit is going to get with Finn to help facilitate this. Once we have access, I'll need to:

- [ ] delete images that have been successfully ingested ([#154](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/154))
- [ ] update species-ocr code ([#3](https://github.com/NHMDenmark/Species-OCR/issues/3))
- [ ] update species-web code ([#3](https://github.com/NHMDenmark/Species-OCR/issues/3)) - for this one, I don't need remote access because it's currently hosted on a linux server I have access to but I can't make this change until the species-ocr code has been updated

**Comment by beckerah** [comment]
I updated the species-ocr code so that it now retrieves the barcodes for species-web. I also updated the .env file to point to the new location of the species-web db.

**Comment by beckerah** [comment]
Bhupjit has migrated species-web to a new server so I now need to:

1. figure out how to access the db on the new server
2. figure out how to access the code on the new server

**Comment by beckerah** [comment]
Updates have been pushed to the newly migrated species-web code. Testing notes will go here: [#4](https://github.com/NHMDenmark/Species-Web/issues/4).
